### ISSUE TITLE
Android demo for SPICE model

### ISSUE THREAD

**Issue by khanhlvg** [ml-gde/e2e-tflite-tutorials#10]
@farmaker47 is working on a sample app that implements the [pitch detection (SPICE) model](https://tfhub.dev/google/spice/2) on Android.

You can find the app source code [here](https://github.com/farmaker47/Pitch_Estimator)

**Comment by farmaker47** [comment]
Working on pitch detection (SPICE) [model](https://tfhub.dev/google/spice/2) I tried to do some inference with the use of .tflite model I got from [here](https://tfhub.dev/google/lite-model/spice/1) inside a colab notebook. I used below code:

`import numpy as np
import tensorflow as tf

# Load the TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="lite-model_spice_1.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test the model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)`

that I copied from Tensorflow web [page](https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_python).

Execution of the colab cell stops with crash:

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-19-dec681e3d8fc> in <module>()
      1 # Load the TFLite model and allocate tensors.
      2 interpreter = tf.lite.Interpreter(model_path="/content/lite-model_spice_1.tflite")
----> 3 interpreter.allocate_tensors()
      4 
      5 # Get input and output tensors.

1 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py in allocate_tensors(self)
    240   def allocate_tensors(self):
    241     self._ensure_safe()
--> 242     return self._interpreter.AllocateTensors()
    243 
    244   def _safe_to_run(self):

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py in AllocateTensors(self)
    108 
    109     def AllocateTensors(self):
--> 110         return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
    111 
    112     def Invoke(self):

RuntimeError: tensorflow/lite/kernels/pad.cc:76 SizeOfDimension(op_context->paddings, 0) != op_context->dims (1 != 0)Node number 8 (PAD) failed to prepare.`

Any help will be appreciated. 

Thank you!

**Comment by khanhlvg** [comment]
I changed 2 things:
* Use tf-nightly as Flex ops (Select TF ops) in the model is only available via TF Lite Python API in TF Lite 2.3 and above.
* As this is a dynamic shape model, resize the input shape to match with the input array.

https://colab.research.google.com/gist/khanhlvg/7027020c14bb343878b0b434a0dff105/spice-model-tf-lite.ipynb

I was able to run inference with the model but the result looks a bit off. Let me check with Gus to see if the model is correctly converted to TF Lite. 

Meanwhile, were you able to run the model on Android? I remembered that you shared some result.

**Comment by farmaker47** [comment]
Model on android (.tflite) results:
![phone](https://user-images.githubusercontent.com/26084498/87933768-84caa680-ca96-11ea-90eb-3e97045722ab.JPG)

Model on colab (saved model format) results:
![colab](https://user-images.githubusercontent.com/26084498/87933822-9ad86700-ca96-11ea-9b7d-e3f567dce331.JPG)

I just wanted to know why I cannot run .tflite on colab. 

That issue does not impact my developing progress on mobile.

**Comment by khanhlvg** [comment]
Gus provided a guide on how to run on Colab. Here is the updated [notebook](https://colab.research.google.com/gist/khanhlvg/7027020c14bb343878b0b434a0dff105/spice-model-tf-lite.ipynb)

**Comment by farmaker47** [comment]
I was able to run inference with .tflite model with notebook that @khanhlvg and @Gus has provided.

Output from colab:
![colab_2](https://user-images.githubusercontent.com/26084498/88027836-805ac800-cb40-11ea-8ff8-6f5c95238963.JPG)

Output from phone:
![mob](https://user-images.githubusercontent.com/26084498/88027865-8c468a00-cb40-11ea-964b-5805f1546891.JPG)

The final colab [notebook](https://colab.research.google.com/drive/1_H0ThLC2iaMdJgfvNjf5T0au1P4Qd2cB?usp=sharing)

A dummy audio [file](https://drive.google.com/file/d/1wP7F_TaaUmsaR8iJUoS4ZzLh7Kqdppc3/view?usp=sharing) to use inside notebook.

**Comment by farmaker47** [comment]
[Android code](https://github.com/farmaker47/Pitch_Estimator) already logs correct notes.

Output for the **same audio file** ->

From colab notebook:
![colab](https://user-images.githubusercontent.com/26084498/88770962-36e52b00-d187-11ea-850f-fd721754a754.JPG)

From mobile phone:
![mobile](https://user-images.githubusercontent.com/26084498/88770989-42385680-d187-11ea-943b-d9e6e0a3bc3a.JPG)

Next steps =  Show notes on screen and create a "live effect" with a musical pentagram.

**Comment by khanhlvg** [comment]
Thanks @farmaker47 for making a lot of good progress on the sample! Could you share the recent updates here as well?

Here are some suggestion for finalizing the sample and get ready to publishing. We'd like to feature them on TensorFlow Twitter account to spread the word.
* Create a video to demo the app. It should have both the app screen recording and the sound that it detects.
* Clean up this [notebook](https://github.com/farmaker47/Pitch_Estimator/blob/master/Copy_of_Pitch_Detection_with_SPICE.ipynb) and remove irrelevant content. I think the purpose of the notebook is to show how to run inference with the TF Lite model, right? Could you also check why the formatting on GitHub is broken?
* Update the README file to mention the notebook, the demo video and add an app screenshot to make it more visual.
* Add a link to the app to [awesome-tflite](https://github.com/margaretmz/awesome-tflite) repo

Thanks again for your contribution, George!

**Comment by farmaker47** [comment]
Emulator cannot open application and after extensive debugging the problem is with:

> implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly'  

With this dependency AS is producing an APK of   **311MB**(!!!!!!!!!)  which is loaded correctly on physical devices and runs without problems producing results. But the emulator cannot load it and crashes at the beginning giving:

> 2020-08-09 11:01:38.726 13126-13126/com.george.pitch_estimator A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xfffffff4 in tid 13126 (pitch_estimator), pid 13126 (pitch_estimator)

 
Without this dependency AS is producing a 32MB APK which is loaded on physical devices and emulator without problems....but then application cannot produce results (on both devices and emulator) giving:

> 2020-08-09 10:42:19.427 10582-10749/com.george.pitch_estimator E/EXCEPTION: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
>     Node number 62 (FlexRFFT) failed to prepare.

@khanhlvg @hoitab please advise me

**Comment by khanhlvg** [comment]
I tested on my app and found that select ops added about 90MB to the APK size (going from 25.7MB to 116.5MB). Your size change is much larger than that so can you [clear your local gradle cache](https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache) to pull the latest version of select ops library and try again?

In practice, we don't include the whole select ops binary to the production app but select only the ops that are needed for the model. We're working on the guide of "selective build" and will publish it soon.

The error `Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.` is expected, as the FlexRFFT is only available in select ops library.

**Comment by farmaker47** [comment]
No luck with cleaning local gradle cache. From 332 MB to 324MB after cleaning. 
I do not know if you built it and loaded it on your emulator. Please inform if at your computer at least loads correctly on emulator.

I will prepare myself with screen mirroring app. I think we will be good to go with this option!!

Thanks

**Comment by khanhlvg** [comment]
I asked a TFLite engineer to investigate the size difference and it turned out that APK compression logic involves some uncertainty around the compression ratio. If we extract my APK and your APK, the total size are almost the same.

I could also run your [app](https://github.com/farmaker47/Pitch_Estimator) on an Android Emulator. Maybe your emulator didn't have enough memory. I allocate 4GB RAM for my emulator.

**Comment by farmaker47** [comment]
Thank you Khanh for investigating this,

For the meeting I am ready with phone mirroring. I will check tomorrow with
more memory.



Στις Πέμ, 13 Αυγ 2020 στις 10:17 π.μ., ο/η Khanh <notifications@github.com>
έγραψε:

**Comment by farmaker47** [comment]
> Thanks @farmaker47 for making a lot of good progress on the sample! Could you share the recent updates here as well?
> 
> Here are some suggestion for finalizing the sample and get ready to publishing. We'd like to feature them on TensorFlow Twitter account to spread the word.
> 
> * Create a video to demo the app. It should have both the app screen recording and the sound that it detects.
> * Clean up this [notebook](https://github.com/farmaker47/Pitch_Estimator/blob/master/Copy_of_Pitch_Detection_with_SPICE.ipynb) and remove irrelevant content. I think the purpose of the notebook is to show how to run inference with the TF Lite model, right? Could you also check why the formatting on GitHub is broken?
> * Update the README file to mention the notebook, the demo video and add an app screenshot to make it more visual.
> * Add a link to the app to [awesome-tflite](https://github.com/margaretmz/awesome-tflite) repo
> 
> Thanks again for your contribution, George!

Hi Khanh,

- Video demo of the project [here](https://youtu.be/v1d3o4r40PQ)
- I have changed my draft colab notebook with the one that is provided inside tensorFlow Hub
- I have updated README file as you suggested
- Added a link to [awesome-tflite](https://github.com/margaretmz/awesome-tflite) repo

I have have already finished version 2 of project with more words of the song and seamless work of app during configuration changes.

**Comment by khanhlvg** [comment]
Thanks George for the update!

Re: your question:

> Pitch detector application version 2 is on its way where there will be a seamless operation on mobile configuration changes and more words of the song on screen!
> 
> I have noticed that when the interpreter is initialized I get this message in Logcat:
> 
> com.george.pitch_estimator I/tflite: TfLiteFlexDelegate delegate: 18 nodes delegated out of 303 nodes with 1 partitions.
> 
> Can you please explain a little bit about that?
> Is something that I can do to improve performance?

Flex delegate is the TF Lite engine to run TF [select ops](https://www.tensorflow.org/lite/guide/ops_select). As the SPICE model contains some ops that are not TFLite builtin, it requires Flex delegate to run.
It's just a FYI log, telling you that 18 of the ops in your model is run on Flex delegate. There's nothing that can be done on the user side for performance improvement here.

**Comment by farmaker47** [comment]
Thanks for clarifying the issue with Flex delegate. It is nice to know how things work under the hood!

FYI version 2 of Pitch Detector [project](https://github.com/farmaker47/Pitch_Estimator) is ready!
After testing it I can assure that:
- Microphone gain is at acceptable level and can collect quality sound even with whispers.
- Output of the model is exactly the same as the output of the provided colab notebook. (Use generated .wav file inside Pitch Detector folder in phone's internal storage to verify if you have time).
- Application works seamlessly at configuration changes.

Also at the beggining of singing someone has to wait approximately 2,3 seconds for the first notes to appear. 2 seconds are for collecting the first part of singing and 0.3 for inferring.

Please when you find time build it, run it on your phone and come with suggestions so I can proceed with the blog post.

Thank you.

**Comment by khanhlvg** [comment]
Thanks George!

I tried the app but it crashed with this error right after I press the "fish" button and start singing.

```
2020-08-25 10:30:44.050 29962-29962/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.george.pitch_estimator, PID: 29962
    kotlin.KotlinNullPointerException
        at com.george.pitch_estimator.SingRecorder.writeWav(SingRecorder.kt:518)
        at com.george.pitch_estimator.singingFragment.SingingFragmentViewModel$doInference$2.invokeSuspend(SingingFragmentViewModel.kt:115)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by farmaker47** [comment]
Too bad!
I started working on it...


Is your device Pixel 3?

**Comment by farmaker47** [comment]
Problem is solved!

It seems that there is an issue with the internal storage Permission.
Application writes every .wav file to internal storage for the user to have the ability to compare results with colab notebook.
This feature is optional and can be deleted in future versions if is not desired.

I know that pop up dialog info is a little misleading BUT (for this app version) this permission is mandatory for app to work.
I have updated [github repo](https://github.com/farmaker47/Pitch_Estimator) to make 2 permissions mandatory. If you think this feature doesn't need to exist please inform me to erase it.

If you do not want to build again comment out line where file is written inside internal storage at SingingFragmentViewModel.kt line 115. If with this still doesn't work build again with the latest commit.

Please after this commit build and check that everything works as expected and notes appear on screen.

Thank you

**Comment by khanhlvg** [comment]
Thanks for fixing the issue, George! And sorry for the delay in my response as I has been busy with several things this week.

I think the permission is fine, given this is just a demo app. Can you add a short explanation on the README file and add a comment in the code that request the permission for those who wonder why the permission is required.

Let me close this issue as the app is now fully working :)
