### ISSUE TITLE
Converting EAST to TFLite

### ISSUE THREAD

**Issue by sayakpaul** [ml-gde/e2e-tflite-tutorials#14]
Contributors: @sayakpaul

**Comment by sayakpaul** [comment]
PyImageSearch has got this blog post [**OpenCV Text Detection (EAST text detector)**](https://www.pyimagesearch.com/2018/08/20/opencv-text-detection-east-text-detector/). EAST was proposed in [An Efficient and Accurate Scene Text Detector](https://arxiv.org/abs/1704.03155). 

From the blog post:
> The EAST pipeline is capable of predicting words and lines of text at arbitrary orientations on 720p images, and furthermore, can run at 13 FPS, according to the authors.

I decided to convert the EAST frozen inference graph to TF Lite and prepare a Colab Notebook. It can be found [here](https://github.com/sayakpaul/Adventures-in-TensorFlow-Lite/blob/master/EAST_TFLite.ipynb). Some results:

![image](https://user-images.githubusercontent.com/22957388/88285417-a9c84f00-cd0c-11ea-8420-de7da82ff7f4.png)

![image](https://user-images.githubusercontent.com/22957388/88285524-df6d3800-cd0c-11ea-9b3d-59898d23ed45.png)

The TFLite model files are heavy for a mobile application I'd say 24 MB and 46 MB (dynamic-range quantized and float16 quantized respectively). The TFLite models can be downloaded from [here](https://storage.googleapis.com/east_tflite/east_tflite_files.zip). 

@khanhlvg and @margaretmz FYI.

**Comment by sayakpaul** [comment]
I have added the int8 (fully int8) model as well and it can be downloaded from [here](https://storage.googleapis.com/east_tflite/east_model_int8.tflite).

**Comment by sayakpaul** [comment]
@khanhlvg should we go for publishing this to TF Hub? Also, if we were to add metadata what reference do we have?

**Comment by khanhlvg** [comment]
> @khanhlvg should we go for publishing this to TF Hub?

Sure, please publish it on TF Hub.

> Also, if we were to add metadata what reference do we have?

My understanding is that this model is an object detection model but instead of detecting objects, it detects text in the scene. Is that correct? If that's the case, we can populate it with object detection metadata. Let me see if object detection metadata is ready first but please expect some delays as the team is currently blocked with some time-sensitive work.

An alternative is to publish a v1 without metadata. We can populate metadata and release v2 later.

**Comment by khanhlvg** [comment]
> Furthermore, would you be able to benchmark the models on your Pixel 4?

Sure.
* `east_model_fp16.tflite` model couldn't run on GPU as it's dynamic shape. Could you export a fixed shape model? The model shape should be the same as the training data.
* `east_model.tflite` on Pixel 4 CPU 4 threads
```
adb shell /data/local/tmp/benchmark_model \
  --graph=/data/local/tmp/east_model.tflite \
  --input_layer=input_images \
  --input_layer_shape=1,384,384,3

Inference timings in us: Init: 1884, First inference: 272513, Warmup (avg): 255986, Inference (avg): 239257
```

* `east_model_int8.tflite` on Pixel 4 CPU 4 threads
```
adb shell /data/local/tmp/benchmark_model \
  --graph=/data/local/tmp/east_model_int8.tflite \
  --input_layer=input_images \
  --input_layer_shape=1,384,384,3

Inference timings in us: Init: 2217, First inference: 272692, Warmup (avg): 255606, Inference (avg): 238269
```

**Comment by sayakpaul** [comment]
Thanks, @khanhlvg. 

> My understanding is that this model is an object detection model but instead of detecting objects, it detects text in the scene. Is that correct? If that's the case, we can populate it with object detection metadata. Let me see if object detection metadata is ready first but please expect some delays as the team is currently blocked with some time-sensitive work.

yes, correct. Should be similar to detection metadata. Totally understandable regarding the delay factor. 

> An alternative is to publish a v1 without metadata. We can populate metadata and release v2 later.

Let's do it then 👍 

> east_model_fp16.tflite model couldn't run on GPU as it's dynamic shape. Could you export a fixed shape model? The model shape should be the same as the training data.

Sure, I will do that. 

Quick question: What are your thoughts in general on the inference time of the models?

**Comment by khanhlvg** [comment]
> Quick question: What are your thoughts in general on the inference time of the models?

I feel that it's on the slower side of object detection models but inference side largely depends on model input size. I run the benchmark on 384x384 image but if the model was trained on 256 x 256 and can perform well with that lower resolution, then that will be a huge speed up factor.

IMO text detection doesn't need to run on video so inference time below 1s is still very useful.

**Comment by sayakpaul** [comment]
@khanhlvg thanks for providing these additional pointers. I exported the [float16 model](https://storage.googleapis.com/east_tflite/east_model_float16.tflite) with a fixed shape (`1, 320, 320, 3`). I tried with other (lower) shapes but the results were poor (which seemed quite obvious as the (320x320) was the training dimension. 

The float16 model has now fixed shape as you can see:

![image](https://user-images.githubusercontent.com/22957388/88532508-59116880-d022-11ea-92ef-2a89f91496c7.png)

I had to parse the frozen graph first and then load that into a concrete a function. After this, I was able to set the input shape of the concrete function and use it to export the model. [This blog post](https://leimao.github.io/blog/Save-Load-Inference-From-TF2-Frozen-Graph/) helped in the concrete function loading part. Everything is updated in the [Colab Notebook](https://github.com/sayakpaul/Adventures-in-TensorFlow-Lite/blob/master/EAST_TFLite.ipynb) I mentioned before. If you could give it a quick look and let me know your thoughts that would be great. Also, as a sanity check would you be able to benchmark this float16 model?

**Comment by khanhlvg** [comment]
If you convert from frozen graph, you can fix the input shape like this:
```
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
    graph_def_file='/content/opencv-text-detection/frozen_east_text_detection.pb', 
    input_arrays=['input_images'],
    output_arrays=['feature_fusion/Conv_7/Sigmoid', 'feature_fusion/concat_3'],
    input_shapes={'input_images': [1, 320, 320, 3]}
)

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]
```

I had to reconvert the graph using TF 2.2 because the tf-nightly version use a newer Conv2D ops that wasn't supported by TF Lite GPU delegate yet. Here is the inference speed. It's definitely fast enough for still image inference 👍 
```
Inference timings in us: Init: 3042360, First inference: 106028, Warmup (avg): 97403.2, Inference (avg): 111847
```

**Comment by sayakpaul** [comment]
Okay cool. Thanks, @khanhlvg. Would you advise me to reconvert the models in TF 2.2 before uploading them to TF Hub?

**Comment by khanhlvg** [comment]
> Would you advise me to reconvert the models in TF 2.2 before uploading them to TF Hub?

Yes please convert using TF 2.2 with 320 x 320 fixed shape input as this model was trained on 320 x 320 images and likely work best on that resolution. Unlike the image -> image models where using high resolution input images will preserve the details for the output images, I don't see much benefit on providing a dynamic shape model in this object detection model.

> Update: When I tried converting after specifying input_shapes argument the converted model became 46 MB (float16) while when I was using concrete functions it was not the case (the float16 model was about 24 MB). Is this a known behavior?

I think in your notebook, you forgot to set ```converter.target_spec.supported_types = [tf.float16]``` when converting the fp16 model. Fp16 model should be twice larger than int8 model.

**Comment by sayakpaul** [comment]
Thank you, @khanhlvg. PR has been created: https://github.com/tensorflow/hub/pull/647.

**Comment by sayakpaul** [comment]
@khanhlvg 

Results on my humble MacBook Air (13-inch, 2017) (Processor: 1.8 GHz Intel Core i5) (Memory: 8 GB 1600 MHz DDR3):

```shell
$ text_detection_video.py --east east_model_float16.tflite
[INFO] starting video stream...
[INFO] elasped time: 73.27
[INFO] approx. FPS: 1.17
```

**TensorFlow version**: 2.3.0 
**Model**:  [float16](https://github.com/sayakpaul/Adventures-in-TensorFlow-Lite/releases/download/v0.6.0/east_model_float16.tar.gz)

Demo available [here](https://www.youtube.com/watch?v=CpywwaAmHPs). 

For folks that might be interested in this, I have created a separate gist [here](https://gist.github.com/sayakpaul/24314074d16018c1ce1b7699cc8395ab#file-text_detection_video-py).

**Comment by sayakpaul** [comment]
Published on TF Hub: https://tfhub.dev/sayakpaul/lite-model/east-text-detector/dr/1.

**Comment by sahasraa** [comment]
hi @sayakpaul  @khanhlvg  can you please share me the inference script for D.range and float16 quantized models?
also could you help me understand this.. my original model size is 96.7mb, after conversion, normal tflite is 24.7mb, and dynamic range.tflite is 24.7mb.  i understand that using dynamic range size is reeduced by 4x  but why is normal tflite and dynamic range are of both same size. is it even possible? @khanhlvg @sayakpaul please reply...
thanks.
