### ISSUE TITLE
Converting keras_ocr to TFLite

### ISSUE THREAD

**Issue by sayakpaul** [ml-gde/e2e-tflite-tutorials#15]
@khanhlvg as you might know [`keras_ocr`](https://pypi.org/project/keras-ocr) is a pretty popular repo for not only just making inference for OCR but also it allows us to fine-tune on our own datasets. So, I thought of converting the pre-trained models to TFLite. 

There are two models to take care of:
- The detection model to actually localize text in an image
- The recognizer model to actually recognize what characters are present in the localized segment of the image

The issue thread provides some more context on generating a `.pb` files of the model graphs with weights. I tried converting the frozen graph of the recognizer to TFLite [on Colab](https://colab.research.google.com/gist/sayakpaul/c93058417ae26eee6fe0eec6f90ea8a9/-keras-ocr-tf-onnx.ipynb) but the session crashed.

**Comment by khanhlvg** [comment]
Sorry somewhat this issue slipped from my inbox.

I tried running your notebook but it failed in early stage.
![image](https://user-images.githubusercontent.com/5379361/92850185-19aea800-f427-11ea-87f1-7c3035f533ee.png)

**Comment by sayakpaul** [comment]
Hi @khanhlvg. 

If you change the `from . import tools` import to `import tools` in `/content/keras-ocr/keras_ocr/tools.py` I think it would work. Sorry, I forgot to include this note in the notebook.

**Comment by khanhlvg** [comment]
I fixed that error and encounter another one.
![image](https://user-images.githubusercontent.com/5379361/92868240-75cff700-f43c-11ea-8bf9-f37126c622a0.png)

Can you send me the saved_model then?

**Comment by sayakpaul** [comment]
@khanhlvg actually I don't have that saved. But I will get to when I can, expect some delay, though.

**Comment by sayakpaul** [comment]
This thread is to be followed - https://github.com/ml-gde/e2e-tflite-tutorials/issues/38.
