### ISSUE TITLE
Style transfer video freeze

### ISSUE THREAD

**Issue by khanhlvg** [ml-gde/e2e-tflite-tutorials#16]
@farmaker47
I tried your style transfer for video [app](https://github.com/farmaker47/video_style_transfer) on both Pixel 3 (OpenCL) and Pixel 1 (OpenGL) and they both worked fine with GPU. 
Here is the screen recording on my Pixel 3: https://youtu.be/oT9gH6OHXUI

Could you share more about the issue you had with GPU?

**Comment by farmaker47** [comment]
Hi Khanh,

Thank you for testing this.

 But from video it is not clear if you move the screen up and then down
when GPU is on. Can you do this ...move the screen or scrolling fast the
recycler view when GPU is on??

Please share the results when you do this

Thanks

Στις Πέμ, 13 Αυγ 2020, 1:06 μ.μ. ο χρήστης Khanh <notifications@github.com>
έγραψε:

**Comment by khanhlvg** [comment]
Yes I can do it without any problem on my Pixel 3 ([video](https://youtu.be/P9kDMsryLP4))

**Comment by farmaker47** [comment]
Ok nice!!

I will share later a video of my phone and the specs of the device.

Στις Πέμ, 13 Αυγ 2020, 1:25 μ.μ. ο χρήστης Khanh <notifications@github.com>
έγραψε:

**Comment by farmaker47** [comment]
Hi Khanh,

I send you a screen recording of my phone. The first 6 seconds are with CPU
usage. You can see that it freely moves up and down and recycler view goes
fast to the last element. Then I switch to GPU and there is a lag in moving
screen up and down and when I fling the recycler view there is a stop (at
moving) and then moving is continuing until the last or first element.
 Screenrecord.mp4
<https://drive.google.com/file/d/1YVwRLg1qWSVRqL1hQqLYPbcuxW6mxzxB/view?usp=drive_web>
These are the specs of my phone:
https://www.gsmarena.com/xiaomi_redmi_note_6_pro-9333.php
Sorry but I cannot find info about OpenCL or OpenGL for this phone.

Please also consider reviewing the Medium
<https://medium.com/@farmaker47/android-implementation-of-video-style-transfer-with-tensorflow-lite-models-9338a6d2a3ea>
blog
post when you have time before I post it on LinkedIn.

Thanks,
George

Στις Πέμ, 13 Αυγ 2020 στις 1:28 μ.μ., ο/η George Soloupis <
farmaker47@gmail.com> έγραψε:

**Comment by farmaker47** [comment]
Searching a little bit more I found specifications for my phone's graphic card. (Adreno 509)
https://www.notebookcheck.net/Adreno-509-vs-Adreno-512_8782_8778.247598.0.html

**Comment by khanhlvg** [comment]
I think the delay is caused by GPU being busy, so that it can't handle screen rendering well. You can try reducing the frame rate (e.g. add a small delay between each frame) and see if it helps avoiding the UI lagging.

**Comment by khanhlvg** [comment]
As the delay was caused by limitation in the phone's hardware spec, I think there's not much we can do about it.
