### ISSUE TITLE
Write a blog post comparing different BERT for mobile models

### ISSUE THREAD

**Issue by khanhlvg** [ml-gde/e2e-tflite-tutorials#23]
[DistilBERT](https://arxiv.org/abs/1910.01108) and [MobileBERT](https://arxiv.org/abs/2004.02984) are currently 2 optimized versions of BERT for mobile. Developers may wonder which version they should use, so we can write a blog post comparing the two.

Some ideas on what to be included in the blog post:
* Include two tasks: text classification and Q&A. Text classification has higher priority though.
* How to train a DistilBERT model and a MobileBERT model on a specific dataset (e.g. SST-2 for text classification).
  * MobileBERT already have a very straightforward [guide](https://www.tensorflow.org/lite/tutorials/model_maker_text_classification) so we can just link to it.
  * DistilBERT has a [conversion guide](https://github.com/huggingface/tflite-android-transformers/blob/master/models_generation/distilbert.py) but we'll need to stitch it with a training guide.
* Comparing multiple dimensions of the trained DistilBERT model vs. MobileBERT model:
  * Model size
  * Accuracy
  * Speed
  * TFLite support (e.g needs select ops or not)

@sayakpaul @farmaker47 @margaretmz FYI, summarizing the discussion on the APAC/EMEA September meeting.

**Comment by sayakpaul** [comment]
Thanks for summarizing this @khanhlvg. I have prior experience of using DistilBERT on text classification tasks. So I think we can start off with that and then make our progress to QnA.

**Comment by sayakpaul** [comment]
I went ahead and created a project repository for this - https://github.com/sayakpaul/BERT-for-Mobile. Will beginning the training soon.

**Comment by sayakpaul** [comment]
Closing this because of inconsistencies in performance.
