### ISSUE TITLE
Few-shot object detector to TFLite

### ISSUE THREAD

**Issue by sayakpaul** [ml-gde/e2e-tflite-tutorials#24]
@khanhlvg the [TFOD API few-shot training example](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tf2_colab.ipynb) uses this checkpoint `ssd_resnet50_v1_fpn_640x640_coco17_tpu-8`. 

Would be nice to see if that fine-tuned model is convertible to TFLite using the recommended instructions. WDYT?

**Comment by khanhlvg** [comment]
Sure, we can try with that model.

**Comment by sayakpaul** [comment]
@khanhlvg the only issue I found there is a lack of guidance to serialize a model trained using the eager mode. I have filed [an issue](https://github.com/tensorflow/models/issues/9224) for that. I will keep this thread updated once I have something.

**Comment by khanhlvg** [comment]
I see. TFLite team also have a plan to work on a few shot training e2e notebook including the conversion to TFLite. Therefore you can prioritize working on the MobileDet models as it's unlikely that anyone will work on it soon.

**Comment by sayakpaul** [comment]
Closing the issue for now then. Feel free to open it up.
