### ISSUE TITLE
Segmentation and Style Transfer project

### ISSUE THREAD

**Issue by farmaker47** [ml-gde/e2e-tflite-tutorials#25]

**Comment by farmaker47** [comment]
I found a useful class that provides several blending modes that would be useful for the project. it is PorterDuff.mode. You can find more info [here](https://developer.android.com/reference/android/graphics/PorterDuff.Mode)

**Comment by khanhlvg** [comment]
I did a quick research and it looks like iOS also natively support Porter-Duff image overlay in `CoreGraphic`. See [this](https://stackoverflow.com/questions/36978908/implementing-porter-duff-compositing-operations-in-ios).

**Comment by sayakpaul** [comment]
Could we please move this discussion to the project's GitHub? https://github.com/margaretmz/segmentation-style-transfer

I am closing this issue for now.
