### ISSUE TITLE
CRAFT TFLITE MODEL

### ISSUE THREAD

**Issue by tulasiram58827** [ml-gde/e2e-tflite-tutorials#36]
Craft is one of the popular architecture for text detection. But the tflite version is not available yet. I would like to convert pretrained model which is trained on SynthText, IC13, IC17 datasets to tflite version.

I already converted to tflite but facing some minor issues. If you would like to proceed me I am happy to add code and will point out the challenges I am facing.

@sayakpaul

**Comment by sayakpaul** [comment]
Please refer to the contribution guidelines here: https://github.com/ml-gde/e2e-tflite-tutorials/wiki/How-to-contribute-to-the-E2E-TFLite-Tutorials%3F.

**Comment by tulasiram58827** [comment]
Thanks for reply.

Step 1. Propose a project idea with either a brief description or an overview page if you wish to add more context about it.

Do I need to propose a project idea by creating a issue.(If yes I already did that.)

**Comment by sayakpaul** [comment]
You can first create a repository dedicated to the project you are proposing. Then maybe commit all the necessary files there and then we can discuss all the problems you are facing there in the repository itself.

**Comment by tulasiram58827** [comment]
Thanks @sayakpaul .

Created the [repo](https://github.com/tulasiram58827/craft_tflite) and added all the necessary files and also created new issue in the repo itself and tagged you.

**Comment by sayakpaul** [comment]
Thanks for your hard work. After we get past the comments (I shared on the repository) please submit a PR to this repository adding the project repo in [here](https://github.com/ml-gde/e2e-tflite-tutorials#end-to-end-tutorials-in-progress).

**Comment by tulasiram58827** [comment]
Hi @sayakpaul . Updated the repo with all the modifications suggested except benchmarking and also create the PR to this repository. Find the PR [here](https://github.com/ml-gde/e2e-tflite-tutorials/pull/37)

**Comment by tulasiram58827** [comment]
Can we publish the models created in this [repo](https://github.com/tulasiram58827/craft_tflite) to tfhub? If yes can you or anyone guide me the process to do so.

**Comment by sayakpaul** [comment]
Tutorials published - 

* https://tulasi.dev/craft-in-tflite
* https://sayak.dev/optimizing-text-detectors/

CRAFT models are also yet to publish on TensorFlow Hub. 

@tulasiram58827 @khanhlvg
