### ISSUE TITLE
SSD MobileNetV2 e2e tutorial (with the latest TFOD API)

### ISSUE THREAD

**Issue by sayakpaul** [ml-gde/e2e-tflite-tutorials#7]
Contributors: @khanhlvg, @sayakpaul

Repository: https://github.com/sayakpaul/E2E-Object-Detection-in-TFLite.

**Comment by sayakpaul** [comment]
@khanhlvg after I was able to successfully export the TFLite model I tried the inference pipeline. But I could not make sense of the interpreter outputs. The format of the TFOD API output and TFLite interpreter output differ. Could you provide me a reference here? 

Here's the TFLite model for your reference: 
[pets_detector.tflite.zip](https://github.com/ml-gde/e2e-tflite-tutorials/files/5196828/pets_detector.tflite.zip)

Here's my [Colab Notebook](https://colab.research.google.com/drive/1ITjgFNoxxU7STgnowXSDld-Ph0FWLSm1?usp=sharing).

**Comment by khanhlvg** [comment]
You can take a look at this object detection [sample](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/raspberry_pi) on how to use the model using Python API.

**Comment by farmaker47** [comment]
Trying to play with Object detection TF.2 I created a [colab notebook](https://colab.research.google.com/drive/1cUKWuSoSLLIJ5wJl2J0fNsTkZPB3ZJJe?usp=sharing) to convert saved models from [TensorFlow v.2 model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) to .tflite.
Apparently despite it is stated that SSD models can be converted I have not managed to succeed in that!

Any thoughts why this conversion of the **specific** ready saved models does not proceed?

**Comment by sayakpaul** [comment]
@farmaker47 in order to be able to convert the graph to TFLite the graph needs to be compatible with the converter. Please either follow the Colab Notebook I mentioned or follow the commands mentioned [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md#step-1-export-tflite-inference-graph).

**Comment by sayakpaul** [comment]
FWIW, I was able to complete the following workflow - 

- Train an SSD MobileNetV2 on the pets dataset using Cloud TPUs.
- Export a TFLite compatible graph from the fine-tuned checkpoints using the [latest exporter script](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md).
- Convert to TFLite and run inference. 

Here's my repository - https://github.com/sayakpaul/E2E-Object-Detection-in-TFLite.. 

@khanhlvg FYI.
