### ISSUE TITLE
Mask R-CNN e2e tutorial

### ISSUE THREAD

**Issue by sayakpaul** [ml-gde/e2e-tflite-tutorials#8]
Contributors: @sayakpaul, @khanhlvg

**Comment by sayakpaul** [comment]
@khanhlvg I tried to again convert Mask R-CNN using the latest converter still no luck. If you remember we had tried this a few months back and we were running into runtime disconnects after the conversion. 

I simplified the workflow a bit and I wanted to share it. 

Here's [my notebook](https://colab.research.google.com/drive/1tdjCjHfLV4h_uwz2oRP2BU53iFGiKgWP?usp=sharing). My guess is that the NMS ops are becoming problmatic for the converter to properly map.

**Comment by khanhlvg** [comment]
@srjoglekar246 will know better but I believe that the NMS ops aren't fully supported yet with TFLite. Sachin only implemented the op specifically for the SSD head as custom ops, hence requiring dedicated export code as you saw in the script in ODT API repo.

**Comment by sayakpaul** [comment]
Okay.

**Comment by srjoglekar246** [comment]
Mask RCNN is supported by TFLite, but only in a very limited way with only the detection heads. See [this comment](https://github.com/tensorflow/tensorflow/issues/34845#issuecomment-573156336) for details.

**Comment by sayakpaul** [comment]
Thanks @srjoglekar246. 

@khanhlvg would you like me to try what Sachin suggested in the comment and prepare a notebook/blog post? 

Since the model is not mobile use-cases would it make sense? LMK.

**Comment by srjoglekar246** [comment]
I don't think so, TBH. We are working on supporting CenterNet & EfficientDets in the coming weeks, those might be better examples of advanced architectures on-device.

**Comment by sayakpaul** [comment]
Oh cool. 

There's a few-shot themed CenterNet Colab Notebook tutorial in the TFOD API repository. While trying it out in eager mode I couldn't figure out how to properly do the export. 

The coming update would definitely be interesting then. 

One point I would note here is that the purpose here is not just to showcase the usage of advanced architectures but also provide the developers a guide to choose between the available options.  Here's a tutorial I published last month that conveys similar ideas: https://sayak.dev/mobiledet-optimization/.
